#[tool.mypy]
#disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = [
  "networkx.*",
  "graphblas_algorithms.*"
]
ignore_missing_imports = true

[tool.flake8]
# Black compatibility
max-line-length = 88
extend-ignore = ["E203", "W503"]

# Per <https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#profile>
[tool.isort]
profile = "black"
